### ISSUE TITLE
commStatus: Error due to complex password

### ISSUE THREAD

**Issue by robcasillas** [tomwpublic/hubitat_flume#15]
After configuring the drive for the first time, I received a commStatus: error. The error ended up being caused by the complex password I was using for my Flume account.  I have since changed the password and that corrected the issue, but thought I'd mention it here. The complex password generating the error was:

Tz=C62u7=X0aw9nHS2d0[<xw[XqY

**Comment by tomwpublic** [comment]
This is due to the `<` character that appears in the string.  Hubitat deliberately broke this with the intent of preventing HTML injection in device and app inputs.  Unfortunately this means that passwords (and any other text inputs) can't contain either `<` or `>`.
