### ISSUE TITLE
Request to change Usage attributes to Number instead of String

### ISSUE THREAD

**Issue by robertctaft** [tomwpublic/hubitat_flume#4]
I was not able to create a condition in Rule Machine that checked if "usageLastMinute" > 0 because it is configured as a String type instead of a Number type.  I changed it to Number and was able to create the condition.  I think this makes those attributes a lot more useful.  I'm not sure if it breaks any other functionality.  Worth updating?

![Screenshot 2021-06-25 113946](https://user-images.githubusercontent.com/51355356/123471042-1184bb00-d5aa-11eb-8907-77f98e8a6ee7.jpg)

**Comment by tomwpublic** [comment]
That seems like a good suggestion @robertctaft .  Would you mind submitting a pull request with the change so that I can review and test?

**Comment by tomwpublic** [comment]
Merged into version 1.1.2.  Thanks @robertctaft !
